console.log("KĀĀlĀĀ checkout script initiated");

let rewards = 0;
const url = [
  "https://kaalaa-server.com/",
  "http://localhost:5050/",
  "https://3e14-154-160-18-118.eu.ngrok.io/",
];
const baseURL = url[0];
const auth = {
  username: "a2FhbGFhX2FjY2VzcyB1c2VybmFtZQ==",
  password: "a2FhbGFhX2FjY2VzcyBwYXNzd29yZA==",
};
const reward = `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="10" cy="8" r="2.5" stroke="black"/>
<path d="M10.5248 1.81414C10.2332 1.52854 9.76679 1.52854 9.4752 1.81414L8.02577 3.23379L5.99702 3.25485C5.5889 3.25908 5.25908 3.5889 5.25485 3.99702L5.23379 6.02577L3.81414 7.4752C3.52854 7.76679 3.52854 8.23321 3.81414 8.5248L5.23379 9.97423L5.25485 12.003C5.25908 12.4111 5.5889 12.7409 5.99702 12.7452L8.02577 12.7662L9.4752 14.1859C9.76679 14.4715 10.2332 14.4715 10.5248 14.1859L11.9742 12.7662L14.003 12.7452C14.4111 12.7409 14.7409 12.4111 14.7452 12.003L14.7662 9.97423L16.1859 8.5248C16.4715 8.23321 16.4715 7.76679 16.1859 7.4752L14.7662 6.02577L14.7452 3.99702C14.7409 3.5889 14.4111 3.25908 14.003 3.25485L11.9742 3.23379L10.5248 1.81414Z" stroke="black" stroke-linejoin="round"/>
<path d="M7 12.5V18.5L10 17.0333M13 12.5V18.5L10 17.0333M10 17.0333V14.1667" stroke="black" stroke-linejoin="round"/>
</svg>
`;
const newReward = `<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M9 3V2C9 1.44772 9.44772 1 10 1C10.5523 1 11 1.44772 11 2C11 2.55228 10.5523 3 10 3H9ZM10 0C11.1046 0 12 0.895431 12 2C12 3.10457 11.1046 4 10 4H9H8H7H6C4.89543 4 4 3.10457 4 2C4 0.895431 4.89543 0 6 0C7.10457 0 8 0.895431 8 2C8 0.895431 8.89543 0 10 0ZM2.5 5C2.22386 5 2 5.22386 2 5.5V8H3L7.5 8V5H2.5ZM7.5 9H3V13.5C3 13.7761 3.22386 14 3.5 14H7.5V9ZM8.5 9H13V13.5C13 13.7761 12.7761 14 12.5 14H8.5V9ZM8.5 8V5H13.5C13.7761 5 14 5.22386 14 5.5V8H13H8.5ZM7 2V3H6C5.44772 3 5 2.55228 5 2C5 1.44772 5.44772 1 6 1C6.55228 1 7 1.44772 7 2Z" fill="white"/>
</svg>
`;
const rewardModal = `<svg width="96" height="96" viewBox="0 0 96 96" fill="rgba(0,0,0,0)" xmlns="http://www.w3.org/2000/svg">
<rect width="96" height="96" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M43 28V22C43 18.6863 40.3137 16 37 16C33.6863 16 31 18.6863 31 22C31 25.3137 33.6863 28 37 28H43ZM37 8C29.268 8 23 14.268 23 22C23 24.9745 23.9276 27.7323 25.5094 30H16C13.7909 30 12 31.7909 12 34V50C12 52.2091 13.7909 54 16 54L16 84C16 86.2091 17.7909 88 20 88H76C78.2091 88 80 86.2091 80 84V54C82.2091 54 84 52.2091 84 50V34C84 31.7909 82.2091 30 80 30H70.4906C72.0724 27.7323 73 24.9745 73 22C73 14.268 66.732 8 59 8C54.5381 8 50.5637 10.0873 48 13.3388C45.4363 10.0873 41.4619 8 37 8ZM20 38V46H44V38H20ZM52 38V46H76V38H52ZM44 56H24V80H44V56ZM52 80V56H72V80H52ZM53 22V28H59C62.3137 28 65 25.3137 65 22C65 18.6863 62.3137 16 59 16C55.6863 16 53 18.6863 53 22Z" fill="#222222"/>
</svg>
`;
const closeModal = `<svg id="kaalaa_claim_close" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M19.0111 6.05016L18.4807 6.58049L13.0613 11.9999L18.4807 17.4193L19.0111 17.9497L17.9504 19.0103L17.4201 18.48L12.0006 13.0606L6.58122 18.48L6.05089 19.0103L4.99023 17.9497L5.52056 17.4193L10.94 11.9999L5.52057 6.58049L4.99024 6.05016L6.0509 4.9895L6.58123 5.51983L12.0006 10.9392L17.4201 5.51983L17.9504 4.9895L19.0111 6.05016Z" fill="black"/>
</svg>
`;
const request_loader = `<div style="width: 232px;"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: white; display: block; shape-rendering: auto;" width="60px" height="60px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="50" fill="none" stroke="#1d0e0b" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
  <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"/>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg></div>`;

async function request(url, obj) {
  try {
    // if (!obj.userId && url !== "user") return;
    var credentials = btoa(
      "a2FhbGFhX2FjY2VzcyB1c2VybmFtZQ==" +
        ":" +
        "a2FhbGFhX2FjY2VzcyBwYXNzd29yZA=="
    );

    const response = await fetch(baseURL + url, {
      method: "POST",
      credentials: "same-origin",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Basic ${credentials}`,
      },
      body: JSON?.stringify(obj),
    });

    const data = await response.json();
    return data;
  } catch (e) {
    if (obj.itemId) {
      hideModal();
    }
    console.error(e);
  }
}

document.onreadystatechange = async () => {
  // console.log("Platform Mobile: ", isMobile);
  if (document.readyState === "complete") {
    let cookie = getCookie("Kaalaa");
    if (cookie) {
      request("reward/history", { userId: cookie }).then((res) => {
        console.log("History results: ", res);
        if (res.status) {
          balance = res.data.balance || balance;
          const redeem = document.getElementById("Kaalaa_redeem");
          if (redeem) redeem.style.display = "flex";
        }
      });
    }
  }
};

function getCookie(name) {
  // Split cookie string and get all individual name=value pairs in an array
  var cookieArr = document.cookie.split(";");

  // Loop through the array elements
  for (var i = 0; i < cookieArr.length; i++) {
    var cookiePair = cookieArr[i].split("=");

    /* Removing whitespace at the beginning of the cookie name
        and compare it with the given string */
    if (name == cookiePair[0].trim()) {
      // Decode the cookie value and return
      return decodeURIComponent(cookiePair[1]);
    }
  }

  // Return null if not found
  return null;
}

function modalDisplay() {
  const modal = document.getElementById("kaalaa_claim_modal");

  if (modal) modal.remove();

  const modalContainer = document.createElement("div");
  modalContainer.className = "modal";
  modalContainer.id = "kaalaa_claim_modal";
  modalContainer.style.display = "flex";

  const modalContentWrapper = document.createElement("div");
  modalContentWrapper.className = "modal-content";

  const modalRewardIcon = document.createElement("div");
  modalRewardIcon.style.justifySelf = "center";
  modalRewardIcon.innerHTML = rewardModal;

  const closeRewardIcon = document.createElement("div");
  closeRewardIcon.className = "modal-close";
  closeRewardIcon.innerHTML = closeModal;

  const loaderIcon = document.createElement("div");
  loaderIcon.innerHTML = request_loader;

  const modalTitle = document.createElement("h2");
  modalTitle.style.fontSize = "18px";
  modalTitle.innerHTML = "$" + balance + " rewards recieved";
  modalTitle.className = "modal-title";

  const modalDesc = document.createElement("p");
  modalDesc.innerHTML = "Input the reward amount you wish to claim below.";
  modalDesc.className = "modal-desc";

  const modalbutton1 = document.createElement("input");
  modalbutton1.placeholder = "$0";
  modalbutton1.id = "claim_reward_value";
  modalbutton1.className = "modal-claim-input";
  modalbutton1.type = "number";

  const modalbutton2 = document.createElement("button");
  modalbutton2.innerHTML = "Claim reward";
  modalbutton2.className = "modal-button";
  modalbutton2.id = "modal-claim-button";
  modalbutton2.style.backgroundColor = "black";
  modalbutton2.style.color = "white";

  const modalStatusWrapper = document.createElement("div");
  modalStatusWrapper.id = "modalStatusContainer";
  modalStatusWrapper.className = "modal-status-container";
  modalStatusWrapper.appendChild(modalbutton1);
  modalStatusWrapper.appendChild(modalbutton2);

  const error = document.createElement("p");
  error.style.fontSize = "14px";
  error.style.color = "red";
  error.style.textAlign = "center";
  error.id = "modal-error-message";

  modalStatusWrapper.appendChild(error);

  modalContentWrapper.appendChild(closeRewardIcon);
  modalContentWrapper.appendChild(modalRewardIcon);
  modalContentWrapper.appendChild(modalTitle);
  modalContentWrapper.appendChild(modalDesc);
  modalContentWrapper.appendChild(modalStatusWrapper);
  modalContainer.appendChild(modalContentWrapper);

  document.body.appendChild(modalContainer);
}

document.addEventListener("click", (e) => {
  const id = e.target.id;

  if (id === "Kaalaa_redeem") {
    modalDisplay();
    return
  }
  if (id === "modal-claim-button") {
    let amount = document.getElementById("claim_reward_value");
    if (amount) {
      const error = document.getElementById("modal-error-message");
      amount = amount.value;
      if (amount < 1) {
        error.innerHTML = "amount can't be less that $1.";
        return;
      }
      if (amount > balance) {
        error.innerHTML =
          "The maximum amount you can claim is $" + balance + ".";
        return;
      }

      const reward_container = document.getElementById(
        "Kaalaa_discount_container"
      );
      if (reward_container) {
        reward_container.style.display = "block";
        const discount = document.getElementById("Kaalaa_reward_amount");
        if (discount) {
          discount.innerHTML = "- $" + amount;
        }

        const cart = document.getElementById("cart_total");
        if (cart) cart.innerHTML = "$" + (160 - parseInt(amount)) || 160;

        const modal = document.getElementById("kaalaa_claim_modal");
        if (modal) modal.remove();
      }
    }
    return
  }
  if (id === "kaalaa_claim_close") {
    hideModal();
    return;
  }
  if (id === "kaalaa_claim_modal") e.target.style.display = "none";
});

function hideModal() {
  const modal = getElementById("kaalaa_claim_modal");
  if (modal) modal.style.display = "none";
}